# **AI Diploma**


### **Data Science**

### Assignment 2

<img src="https://th.bing.com/th/id/R.84611a9f16c2c2ebda65da14c5280e03?rik=YXFlHrjbBApRZQ&pid=ImgRaw&r=0" alt="alternatetext" style="width:1000px;">

### 1) Write a NumPy program to test whether none of the elements of a given array is zero.

In [12]:
import numpy as np

def arr_zero (data):
    count =0
    if np.all(data) == True :
        print ("There are no zero values")
    else:
        for i in range (len(data)):
            for x in range (len(data[0])):
                if data[i,x] == 0 :
                    count+=1
        print (f"There are zero values : {count} Zeros")

data = np.array ([[2,3,2,0],
                [3,8,3,0]])

arr_zero (data)

There are zero values : 2 Zeros


### 2) Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [17]:
import numpy as np

def arr_zero (data):
    count =0
    if np.any(data) == True :
        for i in range (len(data)):
            for x in range (len(data[0])):
                if data[i,x] != 0 :
                    count+=1
        print (f"There are non zero values : {count} Values")
    else:
        print ("There are no non zero values")

data = np.array ([[8,0,0,0],
                [0,0,8,0]])

arr_zero (data)

There are non zero values : 2 Values


### 3) Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [21]:
import numpy as np

def comp (data1,data2):
    comp_ = data1 == data2
    if np.all (comp_) == True :
        print ("Two arrays are equal")
    else:    
        print ("Two arrays are not equal")

data1 = np.array ([[8,0,0,0],
                [0,0,8,0]])
data2 = np.array ([[8,9,0,0],
                [0,0,8,0]])

comp (data1,data2)

Two arrays are not equal


### 5) Write a NumPy program to create an array of the integers from 30 to70.

In [34]:
import numpy as np

np.arange (30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### 4) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [9]:
import numpy as np

print (np.zeros((5,2)))
print (np.ones(10))
print (np.full ((5,2),5))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]]


### 6) Write a NumPy program to create a 3x3 identity matrix

In [4]:
import numpy as np

np.eye (3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 7) Write a NumPy program to generate a random number between 0 and 1

In [50]:
np.random.rand()

0.6679877003658538

### 8) /////Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [49]:
rand_num = np.random.normal(0, 1,15)
print (rand_num)

[-0.40816069 -0.30289762 -0.24789432 -1.08665068 -0.39358849  0.93505775
 -0.39580484 -1.16252191 -3.05242496  1.59290155 -0.4307934   2.43495659
 -1.61912672 -0.36744418  0.29918815]


### 9) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [6]:
data = np.arange (15,56)
print (f"Original data = {data}")
print (f"Edited data = {data[1:-1]}")

Original data = [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Edited data = [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### 10) Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [11]:
import numpy as np

vec = np.linspace (0,10,5,dtype = int)
print (vec)

[ 0  2  5  7 10]


### 11) Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [33]:
arr= np.zeros ((10,10))
arr[0] = 1
arr[-1] = 1
arr[:,0] = 1
arr[:,-1] = 1
print (arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 12) Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [42]:
arr= np.zeros ((5,5),dtype=int)
arr[0,0] = 1
arr[1,1] = 2
arr[2,2] = 3
arr[3,3] = 4
arr[4,4] = 5
arr1 = np.diag ([1,2,3,4,5])
print (arr)
print(arr1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### 13) Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [48]:
arr= np.zeros ((4,4))
arr[::2,1::2] = 1
arr[1::2,::2] = 1
print (arr)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


### 14) Write a Python program to find the two numbers whose product is maximum among all the pairs in a given list of numbers

In [64]:
import random

def maximum (data):
    max = 1
    for i in data:
        for x in data:
           if i!=x and i*x>max:
               max = i*x
               max_n1 = i
               max_n2 = x
    return max,max_n1,max_n2 

data = [8,0,2,3]

x,y,z=maximum (data)
print (f"The two numbers whose product is maximum are {(y,z)}")

The two numbers whose product is maximum are (8, 3)


### 15) Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1

In [67]:
np.random.rand (40)

array([0.77893988, 0.58466744, 0.13922919, 0.06847084, 0.29548006,
       0.3298692 , 0.33377254, 0.83951849, 0.70136022, 0.39842057,
       0.20272686, 0.98459266, 0.17558679, 0.43381296, 0.51438587,
       0.0604928 , 0.03821271, 0.4083124 , 0.57909811, 0.24891329,
       0.61075495, 0.9554425 , 0.08898528, 0.48297988, 0.01708534,
       0.31861108, 0.26902084, 0.92048812, 0.05488405, 0.13780809,
       0.18385912, 0.2639549 , 0.1921124 , 0.28675204, 0.19620085,
       0.14389969, 0.2975805 , 0.46991564, 0.16315642, 0.51342035])

### 16) Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [19]:
import numpy as np 
data2 = np.array ([[8,9,2,0],
                [1,4,8,5]])

n = int (input ("Enter a number"))
a = data2 [data2 > n] 
print (a)

Enter a number 2


[8 9 4 8 5]
